<?php

namespace Database\Seeders;

use App\Models\Team;
use Illuminate\Database\Seeder;

class TeamSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
    	$items = [
    		[
    			'id' => 1,
    			'stadium_id' => 1,
                'conference_id' => 2,
    			'division_id' => 8,
    			'location' => 'Arizona',
    			'name' => 'Cardinals',
    			'name_abbr' => 'ARI',
    			'established' => 1920,
    			'site_url' => 'https://www.azcardinals.com/',
    		],
    		[
    			'id' => 2,
    			'stadium_id' => 2,
                'conference_id' => 2,
    			'division_id' => 7,
    			'location' => 'Atlanta',
    			'name' => 'Falcons',
    			'name_abbr' => 'ATL',
    			'established' => 1966,
    			'site_url' => 'https://www.atlantafalcons.com/',
    		],
    		[
    			'id' => 3,
    			'stadium_id' => 3,
                'conference_id' => 1,
    			'division_id' => 2,
    			'location' => 'Baltimore',
    			'name' => 'Ravens',
    			'name_abbr' => 'BAL',
    			'established' => 1996,
    			'site_url' => 'https://www.baltimoreravens.com/',
    		],
    		[
    			'id' => 4,
    			'stadium_id' => 4,
                'conference_id' => 1,
    			'division_id' => 1,
    			'location' => 'Buffalo',
    			'name' => 'Bills',
    			'name_abbr' => 'BUF',
    			'established' => 1960,
    			'site_url' => 'https://www.buffalobills.com/',
    		],
    		[
    			'id' => 5,
    			'stadium_id' => 5,
                'conference_id' => 2,
    			'division_id' => 7,
    			'location' => 'Carolina',
    			'name' => 'Panthers',
    			'name_abbr' => 'CAR',
    			'established' => 1995,
    			'site_url' => 'https://www.panthers.com/',
    		],
    		[
    			'id' => 6,
    			'stadium_id' => 6,
                'conference_id' => 2,
    			'division_id' => 6,
    			'location' => 'Chicago',
    			'name' => 'Bears',
    			'name_abbr' => 'CHI',
    			'established' => 1920,
    			'site_url' => 'https://www.chicagobears.com/',
    		],
    		[
    			'id' => 7,
    			'stadium_id' => 7,
                'conference_id' => 1,
    			'division_id' => 2,
    			'location' => 'Cincinnati',
    			'name' => 'Bengals',
    			'name_abbr' => 'CIN',
    			'established' => 1968,
    			'site_url' => 'https://www.bengals.com/',
    		],
    		[
    			'id' => 8,
    			'stadium_id' => 8,
                'conference_id' => 1,
    			'division_id' => 2,
    			'location' => 'Cleveland',
    			'name' => 'Browns',
    			'name_abbr' => 'CLE',
    			'established' => 1946,
    			'site_url' => 'https://www.clevelandbrowns.com/',
    		],
    		[
    			'id' => 9,
    			'stadium_id' => 9,
                'conference_id' => 2,
    			'division_id' => 5,
    			'location' => 'Dallas',
    			'name' => 'Cowboys',
    			'name_abbr' => 'DAL',
    			'established' => 1960,
    			'site_url' => 'https://www.dallascowboys.com/',
    		],
    		[
    			'id' => 10,
    			'stadium_id' => 10,
                'conference_id' => 1,
    			'division_id' => 4,
    			'location' => 'Denver',
    			'name' => 'Broncos',
    			'name_abbr' => 'DEN',
    			'established' => 1960,
    			'site_url' => 'https://www.denverbroncos.com/',
    		],
    		[
    			'id' => 11,
    			'stadium_id' => 11,
                'conference_id' => 2,
    			'division_id' => 6,
    			'location' => 'Detroit',
    			'name' => 'Lions',
    			'name_abbr' => 'DET',
    			'established' => 1930,
    			'site_url' => 'https://www.detroitlions.com/',
    		],
    		[
    			'id' => 12,
    			'stadium_id' => 12,
                'conference_id' => 2,
    			'division_id' => 6,
    			'location' => 'Green Bay',
    			'name' => 'Packers',
    			'name_abbr' => 'GB',
    			'established' => 1921,
    			'site_url' => 'https://www.packers.com/',
    		],
    		[
    			'id' => 13,
    			'stadium_id' => 13,
                'conference_id' => 1,
    			'division_id' => 3,
    			'location' => 'Houston',
    			'name' => 'Texans',
    			'name_abbr' => 'HOU',
    			'established' => 2002,
    			'site_url' => 'https://www.houstontexans.com/',
    		],
    		[
    			'id' => 14,
    			'stadium_id' => 14,
                'conference_id' => 1,
    			'division_id' => 3,
    			'location' => 'Indianapolis',
    			'name' => 'Colts',
    			'name_abbr' => 'IND',
    			'established' => 1944,
    			'site_url' => 'https://www.colts.com/',
    		],
    		[
    			'id' => 15,
    			'stadium_id' => 15,
                'conference_id' => 1,
    			'division_id' => 3,
    			'location' => 'Jacksonville',
    			'name' => 'Jaguars',
    			'name_abbr' => 'JAX',
    			'established' => 1995,
    			'site_url' => 'https://www.jaguars.com/',
    		],
    		[
    			'id' => 16,
    			'stadium_id' => 16,
                'conference_id' => 1,
    			'division_id' => 4,
    			'location' => 'Kansas City',
    			'name' => 'Chiefs',
    			'name_abbr' => 'KC',
    			'established' => 1960,
    			'site_url' => 'https://www.chiefs.com/',
    		],
    		[
    			'id' => 17,
    			'stadium_id' => 17,
                'conference_id' => 1,
    			'division_id' => 4,
    			'location' => 'Las Vegas',
    			'name' => 'Raiders',
    			'name_abbr' => 'LV',
    			'established' => 1960,
    			'site_url' => 'https://www.raiders.com/',
    		],
    		[
    			'id' => 18,
    			'stadium_id' => 18,
                'conference_id' => 1,
    			'division_id' => 4,
    			'location' => 'Los Angeles',
    			'name' => 'Chargers',
    			'name_abbr' => 'LAC',
    			'established' => 1960,
    			'site_url' => 'https://www.chargers.com/',
    		],
    		[
    			'id' => 19,
    			'stadium_id' => 18,
                'conference_id' => 2,
    			'division_id' => 8,
    			'location' => 'Los Angeles',
    			'name' => 'Rams',
    			'name_abbr' => 'LAR',
    			'established' => 1937,
    			'site_url' => 'https://www.therams.com/',
    		],
    		[
    			'id' => 20,
    			'stadium_id' => 19,
                'conference_id' => 1,
    			'division_id' => 1,
    			'location' => 'Miami',
    			'name' => 'Dolphins',
    			'name_abbr' => 'MIA',
    			'established' => 1966,
    			'site_url' => 'https://www.miamidolphins.com/',
    		],
    		[
    			'id' => 21,
    			'stadium_id' => 20,
                'conference_id' => 2,
    			'division_id' => 6,
    			'location' => 'Minnesota',
    			'name' => 'Vikings',
    			'name_abbr' => 'MIN',
    			'established' => 1961,
    			'site_url' => 'https://www.vikings.com/',
    		],
    		[
    			'id' => 22,
    			'stadium_id' => 21,
                'conference_id' => 1,
    			'division_id' => 1,
    			'location' => 'New England',
    			'name' => 'Patriots',
    			'name_abbr' => 'NE',
    			'established' => 1960,
    			'site_url' => 'https://www.patriots.com/',
    		],
    		[
    			'id' => 23,
    			'stadium_id' => 22,
                'conference_id' => 2,
    			'division_id' => 7,
    			'location' => 'New Orleans',
    			'name' => 'Saints',
    			'name_abbr' => 'NO',
    			'established' => 1967,
    			'site_url' => 'https://www.neworleanssaints.com/',
    		],
    		[
    			'id' => 24,
    			'stadium_id' => 23,
                'conference_id' => 2,
    			'division_id' => 5,
    			'location' => 'New York',
    			'name' => 'Giants',
    			'name_abbr' => 'NYG',
    			'established' => 1925,
    			'site_url' => 'https://www.giants.com/',
    		],
    		[
    			'id' => 25,
    			'stadium_id' => 23,
                'conference_id' => 1,
    			'division_id' => 1,
    			'location' => 'New York',
    			'name' => 'Jets',
    			'name_abbr' => 'NYJ',
    			'established' => 1960,
    			'site_url' => 'https://www.newyorkjets.com/',
    		],
    		[
    			'id' => 26,
    			'stadium_id' => 24,
                'conference_id' => 2,
    			'division_id' => 5,
    			'location' => 'Philadelphia',
    			'name' => 'Eagles',
    			'name_abbr' => 'PHI',
    			'established' => 1933,
    			'site_url' => 'https://www.philadelphiaeagles.com/',
    		],
    		[
    			'id' => 27,
    			'stadium_id' => 25,
                'conference_id' => 1,
    			'division_id' => 2,
    			'location' => 'Pittsburgh',
    			'name' => 'Steelers',
    			'name_abbr' => 'PIT',
    			'established' => 1933,
    			'site_url' => 'https://www.steelers.com/',
    		],
    		[
    			'id' => 28,
    			'stadium_id' => 26,
                'conference_id' => 2,
    			'division_id' => 8,
    			'location' => 'San Fransisco',
    			'name' => '49ers',
    			'name_abbr' => 'SF',
    			'established' => 1946,
    			'site_url' => 'https://www.49ers.com/',
    		],
    		[
    			'id' => 29,
    			'stadium_id' => 27,
                'conference_id' => 2,
    			'division_id' => 8,
    			'location' => 'Seattle',
    			'name' => 'Seahawks',
    			'name_abbr' => 'SEA',
    			'established' => 1976,
    			'site_url' => 'https://www.seahawks.com/',
    		],
    		[
    			'id' => 30,
    			'stadium_id' => 28,
                'conference_id' => 2,
    			'division_id' => 7,
    			'location' => 'Tampa Bay',
    			'name' => 'Buccaneers',
    			'name_abbr' => 'TB',
    			'established' => 1976,
    			'site_url' => 'https://www.buccaneers.com/',
    		],
    		[
    			'id' => 31,
    			'stadium_id' => 29,
                'conference_id' => 1,
    			'division_id' => 3,
    			'location' => 'Tennessee',
    			'name' => 'Titans',
    			'name_abbr' => 'TEN',
    			'established' => 1960,
    			'site_url' => 'https://www.titansonline.com/',
    		],
    		[
    			'id' => 32,
    			'stadium_id' => 30,
                'conference_id' => 2,
    			'division_id' => 5,
    			'location' => 'Washington',
    			'name' => 'Football Team',
    			'name_abbr' => 'WAS',
    			'established' => 1932,
    			'site_url' => 'https://www.washingtonfootball.com/',
    		],
    	];

    	foreach ($items as $item) {
    		Team::updateOrCreate($item);
    	}
    }
}
