---
openapi: 3.0.0
info:
  title: NFL Laravel Api
  description: This is a NFL API
  contact:
    email: cgressang@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
tags:
- name: conference
  description: Conference calls
- name: team
  description: Team Calls
paths:
  /conference:
    get:
      tags:
      - conference
      summary: List of conferences
      description: |
        List of conferences
      operationId: getConferences
      responses:
        "200":
          description: results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conference'
        "500":
          description: internal server error
  /conference/divisions:
    get:
      tags:
      - conference
      summary: List of conferences divisions
      description: List of conferences divisions
      operationId: getConferenceDivisions
      responses:
        "200":
          description: results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConferenceDivisions'
        "500":
          description: internal server error
  /conference/teams:
    get:
      tags:
      - conference
      summary: List of conferences teams
      description: List of conferences teams
      operationId: getConferenceTeams
      responses:
        "200":
          description: results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConferenceTeams'
        "500":
          description: internal server error
  /team/{teamId}:
    get:
      tags:
      - team
      summary: fetch team by id
      description: Get team by id
      operationId: getTeamById
      parameters:
      - name: teamId
        in: path
        description: Numeric ID of the team to get
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        "500":
          description: internal server error
        "422":
          description: unprocessable entity
components:
  schemas:
    Conference:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: American Football Conference
        abbr:
          type: string
          example: AFC
    Division:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: West
    Team:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        location:
          type: string
          example: Los Angeles
        name:
          type: string
          example: Chargers
        abbr:
          type: string
          example: LAC
        established:
          type: integer
          format: year
          example: 1968
        url:
          type: string
          format: url
          example: https://www.chargers.com
        stadium:
          type: string
          example: SoFi Stadium
        division:
          type: string
          example: West
        conference:
          type: string
          example: AFC
        owners:
          type: array
          items:
            $ref: '#/components/schemas/Owner'
        staff:
          type: array
          items:
            $ref: '#/components/schemas/Staff'
        coaches:
          type: array
          items:
            $ref: '#/components/schemas/Coach'
    ConferenceDivisions:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: American Football Conference
        abbr:
          type: string
          example: AFC
        division_list:
          type: array
          items:
            $ref: '#/components/schemas/Division'
    ConferenceTeams:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: American Football Conference
        abbr:
          type: string
          example: AFC
        team_list:
          type: array
          items:
            $ref: '#/components/schemas/Team'
    Owner:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        first_name:
          type: string
          example: Dean
        last_name:
          type: string
          example: Spanos
    Staff:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        first_name:
          type: string
          example: Tom
        last_name:
          type: string
          example: Telesco
        position:
          type: string
          example: General Manager
    Coach:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        first_name:
          type: string
          example: Brandon
        last_name:
          type: string
          example: Staley
        position:
          type: string
          example: Head Coach
